### ISSUE TITLE
Add fields/entities to schema based on XML spec

### ISSUE THREAD

**Issue by indocomsoft** [source-academy/cadet#161]
- `Question`?
  - [ ] `Library` for the auto-grader (`GRADERDEPLOYMENT`)
- `Assessment`
  - [ ] `number` containing e.g. `M06` (in contrast to title containing, e.g. `Gosperize`)
  - [ ] `story` containing the story name in the game for front-end
  - [ ] `READING` (e.g. Textbook Section 1.1.1 to 1.1.4)

**Comment by indocomsoft** [comment]
@tuesmiddt @ningyuansg @remo5000 @sreycodes I'm listing the additional fields/entities we need to add to accommodate the data from the XML files. Let me know if I miss anything.

**Comment by indocomsoft** [comment]
@ningyuansg Who should be inferring? Should backend send `"M06"` or `"Mission 6"`?

**Comment by ningyuansg** [comment]
Backend can take XML attribute `number` as is and place it in schema field `name`. We'll deal with the rest of the stuff.

**Comment by ningyuansg** [comment]
Seems the better practice too

**Comment by indocomsoft** [comment]
@ningyuansg Alright, so we'll have both `story` and `number`, both stored as is from the XML?

**Comment by ningyuansg** [comment]
Yep

**Comment by tuesmiddt** [comment]
@ningyuansg Do you need back end to do the sorting (by number) or will front end handle it?

**Comment by ningyuansg** [comment]
@tuesmiddt Frontend can handle it

**Comment by tuesmiddt** [comment]
@indocomsoft should we move `library` to `assessment` or keep it at the question level?

**Comment by ningyuansg** [comment]
Keep at question level, since XML specs allow different libraries per question within an assessment, and frontend already relies on each question having a library.

**Comment by tuesmiddt** [comment]
@ningyuansg Sorry I just realised backend needs to be able to do the sorting to add a mission/story field to the `/user` endpoint. Alternatively you do a `GET /assessments` and process from there. What's your preference?

For the `library`, I understand that a question may require a separate library for the autograder. A few questions about this:
1. Does this separate library follow the same schema
2. Does the grading view need this library
3. What should the autograder eventually receive from the backend? (`grading_library || library` vs `[grading_library, library]`)

**Comment by ningyuansg** [comment]
Preferably backend does the sorting and sends us the `story` string as part of the `GET /user` response. This is mainly because we don't want to have to fetch all assessments just to render the game to the user.

1. Yes, it follows the same schema
2. Grading view does not need this separate library, as grading view represents a manual grading
3. Autograder receives `grading_library || library`

**Comment by tuesmiddt** [comment]
@ningyuansg What's the sorting logic?

**Comment by martin-henz** [comment]
Sorting of assessments should be done according to a 2-level ordering:
(1) always show assessments with a due date in the future above assessments with due date in the past.
(2) within each of those two categories, show assessments with an earlier due date above assessments with a later due date.

**Comment by martin-henz** [comment]
I think there are two orthogonal concerns:
(1) A consistent naming scheme for entities: Here I decided that the week of the semester will provide good guidance for the students and the team. I placed a letter in front of the week, for easier disambiguation, see Master Sheet: https://docs.google.com/spreadsheets/d/1NqTOs51QZwv1nSHej2sl2pX7lS9MlHvAhymlB8AEaUM/
(2) Display of assessments to students: I feel that a student will appreciate to see the most "urgent" assessment at the top: That's the assessment whose deadline is the closest in the future. All assessments with a deadline in the past are not "urgent" at all, and therefore should be below all assessments with a deadline in the future.

**Comment by ningyuansg** [comment]
My primary concern wrt to sorting is so that we can decide which assessment model's story should be sent with `GET /user`. To this end, something similar to the original sort logic in source-academy2 as quoted in #148 will do. 

1. Stripping alphabets, compare the numbers first
2. If numbers are equal, then missions > quest > contests

I think the prof is referring to how we sort the list of assessments when we show them to the user on the frontend. We can keep track of that at https://github.com/source-academy/cadet-frontend/issues/233

**Comment by martin-henz** [comment]
Yes, correct. I meant display to students at frontend.

**Comment by ningyuansg** [comment]
Yep, thanks.

**Comment by martin-henz** [comment]
I think we need to clarify what's the purpose of "sorting" here. I was under the impression that it is for display to students, but it seems that you have a different purpose in mind in this discussion. In any case: sorting for display is a frontend issue and such a discussion should go there.

**Comment by ningyuansg** [comment]
Our purpose of sorting is so that we can decide which story to show the students. If a student has the following assessments open to them,

- P1A (attempted)
- P1B (attempted)
- P2A (attempted)
- M2A (attempted)
- P2B
- M2B
- Q2A

Where P2B, M2B and Q2A are not yet attempted by the student. If M2B and Q2A both have a story XML file specified in their assessments XML file, we need to decided which story XML to show the student. Our priority is

- The assessment with a lower number (i.e. earlier weeks) are shown with priority over the larger numbers, while also taking into account the alphabet suffix
- Then, missions with stories are given priority over quests with stories, which are given priority over contests with stories.

This sorting is an internal sorting of 'story priority'.

---

CC @tuesmiddt: My bad, step one doesn't literally strip all alphabets. It should instead just strip the character at index 0. I.e. for M2A and M2B, the A or B is significant. (Compare 2A vs 2B in the first step, rather than A vs B).

**Comment by tuesmiddt** [comment]
@ningyuansg I'm planning to sort by `open_at` and then `type`. Based on the master sheet it looks equivalent and is much cleaner to implement. Let me know if you have any objections. 

Also, for the `attempted` flag, currently we set an assessment's `attempted` to be true whenever a student submits an answer to any of its questions. Should we change this to check if every question has been answered?

**Comment by ningyuansg** [comment]
@tuesmiddt That does sound way cleaner, thanks!

Wrt the `story` of `GET /user`, you're using not `attempted` as a filter predicate for assessments before the sorting step right? Then the current implementation should be just fine.

**Comment by ningyuansg** [comment]
All assessments can map to a story as per the XML specs, so paths can have a story. However, there are no story XMLs written for paths, so the story field is probably empty for paths.

**Comment by ningyuansg** [comment]
Yes, that makes sense. Thanks
