### ISSUE TITLE
Error message shows up on start-up if CS1101S repo is already cloned

### ISSUE THREAD

**Issue by indocomsoft** [source-academy/cadet#197]
According to the log:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/11135744/43902158-ed39696e-9c1b-11e8-8734-e7b972c7c174.png">

**Comment by ningyuansg** [comment]
`CS1101S.clone/0` also fails to throw or indicate an error if the private `CS1101S.git/2` fails.

Using an invalid cs1101s_rsa_key location, starting the server in prod with `PORT=4000 cadet start --updater` logs the following,

```
13:19:46.134 [info] Cloning CS1101S: Started
13:19:47.205 [info] Cloning CS1101S: Done
```

Even though the cloning has failed due to the application being unable to find the private rsa key file.
