### ISSUE TITLE
Implement pagination for /grading endpoint

### ISSUE THREAD

**Issue by indocomsoft** [source-academy/cadet#257]
As of 2018 September 3, noon SGT, this endpoint returns 1MB, which is way too large.

**Comment by jiachen247** [comment]
note that this will break the filter function. I propose aside from the offset and limit we add a search parameter to the grading endpoint.

**Comment by angelsl** [comment]
This is quite important&mdash;for the 1910 database, with 27532 submissions, the grading?group=false endpoint returns 11MB of JSON, and takes about 500ms of DB time and 1.5 seconds in the backend formatting the DB result into JSON.

It also takes about 500MB of memory, so if 2-3 people hit `grading?group=false` at the same time and their requests hit the same node, the backend process will run out of memory and get killed. That's not fatal, since the backend will be auto-restarted, but not ideal.

**Comment by martin-henz** [comment]
@Aulud can you get the pagination to work?

**Comment by angelsl** [comment]
There's an alternative I think, which I'm going to try, which is using PostgreSQL to return JSON directly. If this is efficient enough, I think we can deal with not having server-sided pagination; there are downsides to server-sided pagination, which is that filtering has to be done on the server-side.

It sort of bypasses Ecto (our ORM) but, given that this has shown to be an issue, it is a possible solution and a justifiable breaking of abstraction.

**Comment by angelsl** [comment]
Ok, I've implemented it: https://github.com/source-academy/cadet/commit/b122b762cb60a501c2ee604f57329b37832c0173#diff-dca74d377a1109f871379f3136aec589R797

It now takes about 500ms to respond (acceptable) and it is now much harder to cause an out-of-memory condition :)

I benchmarked: on our usual micro instance (on staging), it handles 500 simultaneous requests without crashing; although it is not able to serve all the requests, it doesn't crash catastrophically.

I now think we do not need server-side pagination.
