### ISSUE TITLE
DevOps: Assessment and Story Infrastructure

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet#361]
We should allow missions to be protected with a URL parameter. We will use the same Source Academy as always, without any need of starting a separate server. We will hide the URL parameter in a shortcut on the desktop of the lab PCs. 

So for example we will have a shortcut "PE" on the desktop, which has the following link:
https://sourceacademy.nus.edu.sg?key=9d8f7g6h5j4k3l2

In this example, the key 9d8f7g6h5j4k3l2 unlocks the PA mission in the assessment section of the Source Academy. The students will need to log in, as usual, using LumiNUS, and go to the PA.

This way, we can:
* avoid installing any other server
* test the PA setup in advance by supplying the correct key, without any time pressure

In addition: log the access of such 'protected' assignment/mission:
- student who accessed and time of access.

**Comment by jiachen247** [comment]
I think this is a really good idea.  It would be mean we can totally bypass setting up a sperate instance for the PE.

How will the implementation and flow look like?
A trivial implementation will look something like this.

1. We add an additional optional field to the mission XML specifying the password.
2. This password can be generated and added days or a week before the PE.
3. When a student requests a password protected mission he/she will be prompted for a password.
4. Validation of this password is done on the backend by comparing the password in the database against the one provided by the student.
5. During the PE we just need to provide students with the key to unlock the missions.

Some issues that I can think of with regards to this implementation
1. Correct me if I'm wrong but avengers have access to the private cs1101s repo. The valid key will be stored in the mission XML which will be accessible to all Avengers.
2. If we do give baggy bounds with regards to the time for the PE. How are we gonna prevent students from logging back into source academy PE mission after the PE since they already have the key?

Maybe we can refine the implementation together. If anyone has any suggestions or ideas do let me know!

**Comment by martin-henz** [comment]
**Some issues that I can think of with regards to this implementation

Correct me if I'm wrong but avengers have access to the private cs1101s repo. The valid key will be stored in the mission XML which will be accessible to all Avengers.**

Yes, to be discussed.

**Comment by martin-henz** [comment]
**Some issues that I can think of with regards to this implementation: If we do give baggy bounds with regards to the time for the PE. How are we gonna prevent students from logging back into source academy PE mission after the PE since they already have the key?**

That's where the logging comes in: We tell the students that they must not try to get access after the exam, and we log and go after anyone who does not follow this advice.

**Comment by jiachen247** [comment]
> **Some issues that I can think of with regards to this implementation: If we do give baggy bounds with regards to the time for the PE. How are we gonna prevent students from logging back into source academy PE mission after the PE since they already have the key?**
> 
> That's where the logging comes in: We tell the students that they must not try to get access after the exam, and we log and go after anyone who does not follow this advice.

Another approach to this is we force students to finialize their submission at the end of the PE. This will mean they can no longer adjust their answers.

**Comment by jiachen247** [comment]
Okay lets split this down to smaller problems

1. Add password feature to assessments
2. Add support for an additional repo

we should consider a private `submodule` implementation over an additional repo as well!! love to hear feedback on this!

**Comment by martin-henz** [comment]
I feel a bit squeamish about storing the password in plain text in the assessment XML.

A more fancy solution: 
(1) The XML specifies that the assessment is password-protected. 
(2) There is a procedure in the backend how to set the password, maybe via ssh with a command-line tool.
(3) The command-line tool is protected so that only sysadmin can call it.
It would work something like this:
% assessmentpasswd
Enter assessment number
> M3B
Enter password
> *********
Re-enter password
> *********
Password successfully changed
%

**Comment by martin-henz** [comment]
I agree. This is all good.

**Comment by martin-henz** [comment]
Note that we now have a separate private repo for Story XML files. See the wiki of the assessment repo for the specification:
https://github.com/source-academy/assessments/wiki
