### ISSUE TITLE
From 2018 team post-mortem: Database schema is a bit too simplified which currently makes it difficult to make changes to the mission data

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet#410]
**Needs discussion over new database schema if changing**

- Could consider changing it
- One of the fields is in JSON (o.o)
- Support submission after the deadline, but mark it as late
- Supporting saving every submission
  - Also solves submission-after-deadline, as we can go back and snoop at the latest submission before the deadline and compare

*Note from Martin:* I strongly support the clean-up of the database schema. Including JSON in the database will be a problem for other changes down the road. I feel the splitting up of the JSON into a proper database columns is a high-priority item.

**Comment by angelsl** [comment]
> One of the fields is in JSON (o.o)
> Including JSON in the database will be a problem for other changes down the road. I feel the splitting up of the JSON into a proper database columns is a high-priority item.

I looked at the columns, and they are these:

- `library`, e.g.

  ```json
  {"chapter": 1, "globals": {}, "external": {"name": "none", "symbols": []}}
  ```

- `grading_library`, similar to above

The above shouldn't be expanded. It's passed straight to the frontend and autograder.

- `question`, e.g.

  ```json
  {
    "choices": [
      {
        "hint": null,
        "content": "Normal order reduction",
        "choice_id": 0,
        "is_correct": true
      },
      {
        "hint": null,
        "content": "Applicative order reduction",
        "choice_id": 1,
        "is_correct": false
      }
    ],
    "content": "### Task 1a: Models of computation I\n\nDuring the lecture, it was mentioned that<snip...>"
  }
  ```

This shouldn't be expanded into extra columns&mdash;this is not really relational data, and expanding it into separate tables would just mean a lot of inefficiency and extra load on PostgreSQL's end to re-assemble the data, since we never only need a single choice or something like that.

Anyway, PostgreSQL has specific support for storing JSON in an efficient format, which we use for this already. (jsonb)

> - Support submission after the deadline, but mark it as late
> - Supporting saving every submission

Do we want these?

**Comment by martin-henz** [comment]
OK, let's keep it in JSON, then. Thanks for taking a close look.
